//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaftalikOdevlerr
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HaftalikOdevlerr()
        {
            this.OgrenciiKayit = new HashSet<OgrenciiKayit>();
        }
    
        public int HaftalikOdevID { get; set; }
        public string VerilenKonu { get; set; }
        public Nullable<System.DateTime> VerilisTarihi { get; set; }
        public Nullable<System.DateTime> TeslimTarihi { get; set; }
        public byte VerilenNot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciiKayit> OgrenciiKayit { get; set; }
    }
}
