//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaftalikOdevler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HaftalikOdevler()
        {
            this.OgrenciKayitlari = new HashSet<OgrenciKayitlari>();
        }
    
        public int HaftalıkOdevID { get; set; }
        public string VerilenKonu { get; set; }
        public System.DateTime VerilisTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public byte VerilenNot { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciKayitlari> OgrenciKayitlari { get; set; }
    }
}
