//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class OdemeVadeleri
    {
        public int OdemeBilgileriID { get; set; }
        public int OgrenciID { get; set; }
        public byte TaksitNo { get; set; }
        public decimal TaksitTutari { get; set; }
        public System.DateTime VadeTarihi { get; set; }
        public bool Odedimi { get; set; }
    
        public virtual OgrenciiKayit OgrenciiKayit { get; set; }
    }
}
