//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sinif
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sinif()
        {
            this.OgrenciiKayit = new HashSet<OgrenciiKayit>();
        }
    
        public int SinifID { get; set; }
        public string SinifBransi { get; set; }
        public int OgretmenID { get; set; }
        public Nullable<System.DateTime> DerslerinBaslangici { get; set; }
        public Nullable<System.DateTime> DerslerinBitisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OgrenciiKayit> OgrenciiKayit { get; set; }
        public virtual OgretmenKayit OgretmenKayit { get; set; }
    }
}
