//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HaftalikOdevler
    {
        public int HaftalıkOdevID { get; set; }
        public string VerilenKonu { get; set; }
        public System.DateTime VerilisTarihi { get; set; }
        public System.DateTime TeslimTarihi { get; set; }
        public byte VerilenNot { get; set; }
    }
}
