//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgrenciKayit
    {
        public int OgrenciID { get; set; }
        public int VeliID { get; set; }
        public int HaftalıkOdevID { get; set; }
        public int SinifID { get; set; }
        public string OgrenciAdi { get; set; }
        public string OgrenciSoyadi { get; set; }
        public int OgrenciNumarasi { get; set; }
        public string OgrenciTcKimlikNo { get; set; }
        public string OgrenciOKulBolumu { get; set; }
        public string OgrenciAdresi { get; set; }
        public string OgrenciPostaKodu { get; set; }
        public string OgrenciSemt { get; set; }
        public string OgrenciSehir { get; set; }
        public byte ToplamTaksitSayisi { get; set; }
        public decimal OdenecekToplamTutar { get; set; }
        public Nullable<System.DateTime> KayitTarihi { get; set; }
    }
}
