//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siniflarr
    {
        public int SinifID { get; set; }
        public string SinifBransi { get; set; }
        public int OgretmenID { get; set; }
        public System.DateTime DerslerinBaslangici { get; set; }
        public System.DateTime DerslerinBitisi { get; set; }
    
        public virtual OgretmenKayit OgretmenKayit { get; set; }
    }
}
