//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DersaneOtomasyonu.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class VeliKayit
    {
        public int VeliID { get; set; }
        public string VeliAdiSoyadi { get; set; }
        public string VeliTcKimlikNo { get; set; }
        public string VeliYakinligi { get; set; }
        public string VeliİsAdresi { get; set; }
        public string VeliEvAdresi { get; set; }
        public string VeliPostaKodu { get; set; }
        public string VeliCepTel { get; set; }
        public string VeliMailAdresi { get; set; }
        public string VeliEgitimDurumu { get; set; }
        public decimal VeliGelirDuzeyi { get; set; }
    }
}
